### PR TITLE
Add autoinstall script for Linux/OSX

### PR DESCRIPTION
**Pull request by Brian3647**

### CODE REVIEW

**Comment by Brian3647** [comment]
`curl https://raw.githubusercontent.com/blade-lang/blade/blob/main/scripts/autoinstall.sh | bash` Gives a 404 now but it wouldn't if the PR is merged

**Comment by mcfriend99** [comment]
This script does not currently point to the `CMakeLists.txt` file and for that reason returns the error:

```
CMake Error: The source directory "/user/home/dir" does not appear to contain CMakeLists.txt.
```

One simple solution could be to cd into the directory before running the make commands.

Also, once that is fixed, the `autoinstall.sh` script should work for OSX as well and you may consider updating the `BUILDING.md` and remove the `Linux only` as this autoinstall script should work on Linux and any Unix system.

**Comment by Brian3647** [comment]
Ok, going to fix it

**Comment by Brian3647** [comment]
Try now, In my computer works (Zorin OS, Linux) but I can't test it in OSX

**Comment by mcfriend99** [comment]
Nice one. Now it works, but I see you are no longer adding the `bin` directory to path as you were doing before which was fine on OSX as well.

The former code for adding to path was working fine on both linux and OSX. Will you be able add it back in??

**Comment by Brian3647** [comment]
Yes, but the script will have to prompt the user to detect which file to use.

If not, if you run `bash scripts/autoinstall.sh` in `zsh` it will add the PATH to `~/.bashrc` and not `~/.zshrc`, for example.

**Comment by mcfriend99** [comment]
That's fine by me. Does that pose any difficulty on your end??

**Comment by Brian3647** [comment]
No, I will add it

**Comment by Brian3647** [comment]
Done

**Comment by Brian3647** [comment]
Something more I have to change?

**Comment by mcfriend99** [comment]
Tested on both Linux and OSX with the following observations:

1. It only works when you download the `autoinstall.sh` script first. For example, using wget and running the script directly. It doesn't work using the command provided.
2. It only works with the default profile `.bashrc`. It fails to add to path once you use specify another profile such ash `.bash_profile`, `.zshrc` etc.

**Comment by mcfriend99** [comment]
Also, on linux it would make sense if we can check if `build-essentials` and `cmake` are installed before proceeding and much more better if we can install them automatically.

Though we can make do without this now, I'm just saying it will be a great addition.

**Comment by Brian3647** [comment]
> Tested on both Linux and OSX with the following observations:
> 
>     1. It only works when you download the `autoinstall.sh` script first. For example, using wget and running the script directly. It doesn't work using the command provided.
> 
>     2. It only works with the default profile `.bashrc`. It fails to add to path once you use specify another profile such ash `.bash_profile`, `.zshrc` etc.

It also works with `.zshrc` and `.bash_profile` if you specify the full path.

**Comment by mcfriend99** [comment]
Noted @Brian3647 . But it still doesn't work with the link given. It only works when it's downloaded first. Also, will it be possible to check for `build-essentials` and `cmake` on linux?? Even if we are not automatically installing it now, at least it makes sense to tell the user to install them first.

**Comment by Brian3647** [comment]
Ok, and for the link, as I said:
> curl https://raw.githubusercontent.com/blade-lang/blade/blob/main/scripts/autoinstall.sh | bash Gives a 404 now but it wouldn't if the PR is merged
That's because the file is now in `https://raw.githubusercontent.com/Brian3647/blade/blob/main/scripts/autoinstall.sh` (my fork)

**Comment by mcfriend99** [comment]
That's exactly the one I used - the one from your fork (`https://raw.githubusercontent.com/Brian3647/blade/blob/main/scripts/autoinstall.sh`), and it didn't work.

**Comment by Brian3647** [comment]
Ok, I'm going to change the BUILDING.md, found the issue

**Comment by mcfriend99** [comment]
Tested again and all it does using the link is show download progress and nothing more.

<a href="https://ibb.co/2hB5kPD" target="_blank">Screenshot-2021-09-04-at-12-00-02</a>

**Comment by mcfriend99** [comment]
> Ok, I'm going to change the BUILDING.md, found the issue

Ok

**Comment by Brian3647** [comment]
Now it also checks for `cmake`, too

**Comment by Brian3647** [comment]
I don't really know how to detect if `build-essentials` is installed

**Comment by mcfriend99** [comment]
Can we take out the cmake check for now and focus on making it run well first. Because the make check is causing it to fail.

<a href="https://ibb.co/2Ntm3t3" target="_blank">Screenshot-2021-09-04-at-12-15-40</a>

**Comment by Brian3647** [comment]
Didn't notice that, I'll fix it in a minute

**Comment by mcfriend99** [comment]
> Can we take out the cmake check for now and focus on making it run well first. Because the make check is causing it to fail.
> 
> [Screenshot-2021-09-04-at-12-15-40](https://ibb.co/2Ntm3t3)

Or better still, fix the `cmake` check.

**Comment by mcfriend99** [comment]
> Didn't notice that, I'll fix it in a minute

Ok. Thanks

**Comment by Brian3647** [comment]
Done

**Comment by mcfriend99** [comment]
There's a little problem with the path added. See the attached screenshot.

<a href="https://ibb.co/k988hxf" target="_blank">Screenshot-2021-09-04-at-12-28-26</a>

The `//` in the path will cause some module imports to fail on linux.

**Comment by Brian3647** [comment]
Ok, going to fix it

**Comment by Brian3647** [comment]
Fixed

**Comment by mcfriend99** [comment]
Update `BUILDING.md` to below so I can merge it:

`bash <(curl -s https://raw.githubusercontent.com/blade-lang/blade/main/scripts/autoinstall.sh)`

**Comment by Brian3647** [comment]
Later, I'm not on the pc now

**Comment by Brian3647** [comment]
Done

**Review by mcfriend99 — APPROVED** [review]
Thanks @Brian3647. Approved!

**Comment by mcfriend99** [comment]
Please chat me up on Gitter (link in README)

**Pull request merged**
